import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/vue'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { createMemoryHistory, createRouter } from 'vue-router'
import AdminTopicPage from './AdminTopicPage.vue'
vi.mock('../admin-api',()=>({listTopics:vi.fn(async()=>({items:[],page:0,size:20,total:0,totalPages:0})),loadTopic:vi.fn(),createTopic:vi.fn(),updateTopic:vi.fn(),removeTopic:vi.fn()}))
vi.mock('../../articles/admin-api',()=>({listAdminArticles:vi.fn(),lookupAdminArticles:vi.fn()}))
vi.mock('../../media/api',()=>({ACCEPTED_IMAGE_TYPES:'image/png',uploadMedia:vi.fn()}))
const article=(id:number,title:string)=>({id,title,slug:`a-${id}`,summary:'',contentType:'ARTICLE',status:'DRAFT',publishedAt:null,scheduledAt:null,coverUrl:null,category:null,tags:[]}) as never
async function mount(){const router=createRouter({history:createMemoryHistory(),routes:[{path:'/admin/topics',component:AdminTopicPage}]});await router.push('/admin/topics');await router.isReady();render(AdminTopicPage,{global:{plugins:[router]}});return router}
afterEach(cleanup)
beforeEach(async()=>{vi.clearAllMocks();const articles=await import('../../articles/admin-api');vi.mocked(articles.listAdminArticles).mockResolvedValue({items:[article(1,'甲'),article(2,'乙')],page:0,size:20,total:2,totalPages:1})})
describe('AdminTopicPage',()=>{
  it('uploads a cover and sends keyboard article ordering',async()=>{const api=await import('../admin-api'),media=await import('../../media/api');vi.mocked(media.uploadMedia).mockResolvedValue({id:9,url:'/cover',storageKey:'x',contentType:'image/png',width:1,height:1});vi.mocked(api.createTopic).mockResolvedValue({} as never);await mount();await screen.findByText('甲');for(const box of screen.getAllByRole('checkbox'))await fireEvent.click(box);await fireEvent.click(screen.getByRole('button',{name:'下移 甲'}));await fireEvent.change(screen.getByLabelText('封面'),{target:{files:[new File(['x'],'c.png',{type:'image/png'})]}});await fireEvent.update(screen.getByLabelText('名称'),'专题');await fireEvent.click(screen.getByRole('button',{name:'保存专题'}));await waitFor(()=>expect(api.createTopic).toHaveBeenCalledWith(expect.objectContaining({coverMediaId:9,articleIds:[2,1]})))})
  it('searches bounded later pages and can select article 21+',async()=>{const api=await import('../../articles/admin-api');vi.mocked(api.listAdminArticles).mockResolvedValueOnce({items:Array.from({length:20},(_,i)=>article(i+1,`文章${i+1}`)),page:0,size:20,total:21,totalPages:2}).mockResolvedValueOnce({items:[article(21,'第二十一篇')],page:1,size:20,total:21,totalPages:2});await mount();await screen.findByText('文章1');await fireEvent.click(within(screen.getByRole('navigation',{name:'文章搜索分页'})).getByRole('button',{name:'下一页'}));await screen.findByText('第二十一篇');await fireEvent.click(screen.getByRole('checkbox'));expect(screen.getByRole('button',{name:'移除 第二十一篇'})).toBeTruthy()})
  it('hydrates every selected title through one bounded bulk lookup and removes chips',async()=>{const topicApi=await import('../admin-api'),articleApi=await import('../../articles/admin-api');vi.mocked(topicApi.listTopics).mockResolvedValue({items:[{id:7,name:'专题',slug:'t',description:'',coverUrl:null,coverMediaId:null,status:'DRAFT',sortOrder:0,articleIds:[21,42]}],page:0,size:20,total:1,totalPages:1});vi.mocked(topicApi.loadTopic).mockResolvedValue({id:7,name:'专题',slug:'t',description:'',coverUrl:null,coverMediaId:null,status:'DRAFT',sortOrder:0,articleIds:[21,42]});vi.mocked(articleApi.lookupAdminArticles).mockResolvedValue([article(21,'第二十一篇'),article(42,'第四十二篇')]);await mount();await fireEvent.click(await screen.findByRole('button',{name:'编辑'}));expect(articleApi.lookupAdminArticles).toHaveBeenCalledTimes(1);expect(articleApi.lookupAdminArticles).toHaveBeenCalledWith([21,42]);await fireEvent.click(await screen.findByRole('button',{name:'移除 第二十一篇'}));expect(screen.queryByRole('button',{name:'移除 第二十一篇'})).toBeNull()})
})
