<template>
  <section class="admin-page"><header class="admin-page__heading"><p class="admin-page__eyebrow">内容组织</p><h1>分类与标签</h1></header><div class="columns">
    <form class="admin-card admin-form" @submit.prevent="saveCategory"><h2>分类</h2><label>筛选范围<select v-model="categoryScopeFilter" @change="applyFilters"><option value="">全部</option><option value="ARTICLE">文章</option><option value="TOOL">工具</option></select></label><label>名称<input v-model="category.name" required></label><label>范围<select v-model="category.scope"><option value="ARTICLE">文章</option><option value="TOOL">工具</option></select></label><label>描述<textarea v-model="category.description"/></label><label>排序<input v-model.number="category.sortOrder" type="number"></label><button class="admin-button">保存分类</button><ul><li v-for="c in categories" :key="c.id">{{c.name}}（{{c.scope}}） <button type="button" @click="editCategory(c)">编辑</button><button type="button" @click="ask('category',c.id,c.name)">删除</button></li></ul><nav aria-label="分类分页"><button type="button" :disabled="categoryPage===0" @click="pageTo('categoryPage',categoryPage-1)">上一页</button><button type="button" :disabled="categoryPage+1>=categoryTotalPages" @click="pageTo('categoryPage',categoryPage+1)">下一页</button></nav></form>
    <form class="admin-card admin-form" @submit.prevent="saveTag"><h2>标签</h2><label>筛选关键词<input v-model="tagKeywordFilter"></label><button type="button" @click="applyFilters">筛选标签</button><label>名称<input v-model="tagName" required></label><button class="admin-button">保存标签</button><ul><li v-for="t in tags" :key="t.id">{{t.name}} <button type="button" @click="editTag(t)">编辑</button><button type="button" @click="ask('tag',t.id,t.name)">删除</button></li></ul><nav aria-label="标签分页"><button type="button" :disabled="tagPage===0" @click="pageTo('tagPage',tagPage-1)">上一页</button><button type="button" :disabled="tagPage+1>=tagTotalPages" @click="pageTo('tagPage',tagPage+1)">下一页</button></nav></form>
  </div><p v-if="error" role="alert">{{error}}</p><dialog ref="dialog" aria-labelledby="taxonomy-delete-title" aria-describedby="taxonomy-delete-description"><h2 id="taxonomy-delete-title">确认删除？</h2><p id="taxonomy-delete-description">删除“{{pending?.name}}”后无法恢复。</p><button @click="remove">确认删除</button><button @click="dialog?.close()">取消</button></dialog></section>
</template>
<script setup lang="ts">
import{nextTick,onMounted,reactive,ref,watch}from'vue';import{useRoute,useRouter}from'vue-router';import type{CategoryRequest,CategoryResponse,TagResponse}from'../../../shared/api/contracts';import{createCategory,createTag,listCategories,listTags,removeCategory,removeTag,updateCategory,updateTag}from'../admin-api'
const route=useRoute(),router=useRouter(),categoryPage=ref(Math.max(0,Number(route.query.categoryPage)||0)),tagPage=ref(Math.max(0,Number(route.query.tagPage)||0)),categoryScopeFilter=ref(String(route.query.scope??'')),tagKeywordFilter=ref(String(route.query.tagKeyword??'')),categoryTotalPages=ref(0),tagTotalPages=ref(0),categories=ref<CategoryResponse[]>([]),tags=ref<TagResponse[]>([]),categoryId=ref<number|null>(null),tagId=ref<number|null>(null),tagName=ref(''),error=ref(''),dialog=ref<HTMLDialogElement>(),pending=ref<{kind:'category'|'tag',id:number,name:string}|null>(null);const category=reactive<CategoryRequest>({name:'',description:'',sortOrder:0,scope:'ARTICLE'})
async function load(){const[c,t]=await Promise.all([listCategories(categoryPage.value,20,categoryScopeFilter.value||undefined),listTags(tagPage.value,20,tagKeywordFilter.value.trim()||undefined)]);categories.value=c.items;categoryTotalPages.value=c.totalPages;tags.value=t.items;tagTotalPages.value=t.totalPages}async function applyFilters(){await router.replace({query:{...route.query,categoryPage:undefined,tagPage:undefined,scope:categoryScopeFilter.value||undefined,tagKeyword:tagKeywordFilter.value.trim()||undefined}})}async function pageTo(key:'categoryPage'|'tagPage',value:number){await router.replace({query:{...route.query,[key]:value||undefined}})}function editCategory(c:CategoryResponse){categoryId.value=c.id;Object.assign(category,c)}function editTag(t:TagResponse){tagId.value=t.id;tagName.value=t.name}async function saveCategory(){try{categoryId.value?await updateCategory(categoryId.value,category):await createCategory(category);categoryId.value=null;Object.assign(category,{name:'',description:'',sortOrder:0,scope:'ARTICLE'});await load()}catch{error.value='分类保存失败'}}async function saveTag(){try{tagId.value?await updateTag(tagId.value,{name:tagName.value}):await createTag({name:tagName.value});tagId.value=null;tagName.value='';await load()}catch{error.value='标签保存失败'}}async function ask(kind:'category'|'tag',id:number,name:string){pending.value={kind,id,name};if(typeof dialog.value?.showModal==='function')dialog.value.showModal();else dialog.value?.setAttribute('open','');await nextTick();dialog.value?.querySelector<HTMLButtonElement>('button')?.focus()}async function remove(){if(!pending.value)return;try{pending.value.kind==='category'?await removeCategory(pending.value.id):await removeTag(pending.value.id);dialog.value?.close();await load()}catch(e:any){error.value=e?.status===409?'仍有内容使用该项，无法删除。':'删除失败'}}watch(()=>route.query,()=>{categoryPage.value=Math.max(0,Number(route.query.categoryPage)||0);tagPage.value=Math.max(0,Number(route.query.tagPage)||0);categoryScopeFilter.value=String(route.query.scope??'');tagKeywordFilter.value=String(route.query.tagKeyword??'');void load()},{deep:true});onMounted(()=>void load())
</script><style scoped>.columns{display:grid;grid-template-columns:1fr 1fr;gap:20px}@media(max-width:760px){.columns{grid-template-columns:1fr}}</style>
