import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/vue'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { createMemoryHistory, createRouter } from 'vue-router'
import { ApiProblem } from '../../../shared/api/problem'
import AdminToolEditorPage from './AdminToolEditorPage.vue'
vi.mock('../admin-api',()=>({loadAdminTool:vi.fn(),updateTool:vi.fn(),createTool:vi.fn(),publishTool:vi.fn(),archiveTool:vi.fn(),removeTool:vi.fn()}))
vi.mock('../../topics/admin-api',()=>({listCategories:vi.fn(async()=>({items:[],page:0,size:50,total:0,totalPages:0})),listTags:vi.fn(async()=>({items:[],page:0,size:50,total:0,totalPages:0}))}))
const base={id:2,name:'旧名',slug:'tool',summary:'摘要',descriptionMarkdown:'# d',officialUrl:'https://example.com',coverMediaId:null,coverUrl:null,category:null,tags:[],featured:false,status:'DRAFT',renderedHtml:'',sortOrder:0,publishedAt:null,createdAt:'x',updatedAt:'x'}
async function mount(){const router=createRouter({history:createMemoryHistory(),routes:[{path:'/admin/tools/:id/edit',component:AdminToolEditorPage},{path:'/admin/tools',name:'admin-tools',component:{template:'<p>tools</p>'}}]});await router.push('/admin/tools/2/edit');await router.isReady();render({template:'<router-view/>'},{global:{plugins:[router],stubs:{MarkdownEditor:{props:['modelValue'],template:'<textarea />'}}}});await screen.findByLabelText('名称');return router}
describe('AdminToolEditorPage',()=>{beforeEach(()=>vi.clearAllMocks());afterEach(cleanup)
  it('saves current fields before publishing and reports visible status',async()=>{const api=await import('../admin-api');vi.mocked(api.loadAdminTool).mockResolvedValue(base as never);vi.mocked(api.updateTool).mockResolvedValue({...base,name:'新名'} as never);vi.mocked(api.publishTool).mockResolvedValue({...base,status:'PUBLISHED'} as never);await mount();await fireEvent.update(screen.getByLabelText('名称'),'新名');await fireEvent.click(screen.getByRole('button',{name:'保存并发布'}));await waitFor(()=>expect(api.updateTool).toHaveBeenCalledWith(2,expect.objectContaining({name:'新名'})));expect(api.publishTool).toHaveBeenCalledWith(2);expect((await screen.findByRole('status')).textContent).toContain('工具已发布');expect(screen.getByText(/当前状态：PUBLISHED/)).toBeTruthy();expect(screen.queryByRole('button',{name:'保存并发布'})).toBeNull();expect(screen.getByRole('button',{name:'归档'})).toBeTruthy()})
  it('keeps request-time edits dirty and preserves a non-slug conflict detail',async()=>{const api=await import('../admin-api');vi.mocked(api.loadAdminTool).mockResolvedValue(base as never);let resolve!:(v:any)=>void;vi.mocked(api.updateTool).mockReturnValue(new Promise(r=>resolve=r));const router=await mount();await fireEvent.update(screen.getByLabelText('名称'),'第一版');await fireEvent.click(screen.getByRole('button',{name:'保存草稿'}));await fireEvent.update(screen.getByLabelText('名称'),'请求期间编辑');resolve({...base,name:'第一版'});await waitFor(()=>expect(api.updateTool).toHaveBeenCalled());const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);await router.push('/admin/tools');expect(router.currentRoute.value.path).toContain('/edit');expect(confirm).toHaveBeenCalled();vi.mocked(api.updateTool).mockRejectedValue(new ApiProblem({title:'Conflict',status:409,detail:'Archived tools cannot be edited'}));await fireEvent.click(screen.getByRole('button',{name:'保存草稿'}));expect((await screen.findByRole('alert')).textContent).toBe('Archived tools cannot be edited')})
  it('labels, describes and focuses the published archive confirmation',async()=>{const api=await import('../admin-api');vi.mocked(api.loadAdminTool).mockResolvedValue({...base,status:'PUBLISHED'} as never);await mount();expect(screen.queryByRole('button',{name:'保存并发布'})).toBeNull();await fireEvent.click(screen.getByRole('button',{name:'归档'}));expect(screen.getByRole('dialog',{name:'确认归档？',description:'归档后工具将不再公开展示。'})).toBeTruthy();expect(document.activeElement).toBe(screen.getByRole('button',{name:'确认归档'}))})
})
