import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/vue'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { createMemoryHistory, createRouter } from 'vue-router'
import { ApiProblem } from '../../../shared/api/problem'
import AdminArticleEditorPage from './AdminArticleEditorPage.vue'

vi.mock('../admin-api', () => ({ createArticle:vi.fn(),updateArticle:vi.fn(),loadAdminArticle:vi.fn(),publishArticle:vi.fn(),scheduleArticle:vi.fn(),archiveArticle:vi.fn(),loadArticleOptions:vi.fn(async()=>({categories:[],tags:[],topics:[]})) }))
vi.mock('../../media/api', () => ({ ACCEPTED_IMAGE_TYPES:'image/png',uploadMedia:vi.fn() }))
const editorStub={props:['modelValue'],emits:['update:modelValue'],template:'<textarea aria-label="正文" :value="modelValue" @input="$emit(\'update:modelValue\',$event.target.value)" />'}
async function mount(path='/admin/articles/new') { const router=createRouter({history:createMemoryHistory(),routes:[{path:'/admin/articles/new',component:AdminArticleEditorPage},{path:'/admin/articles/:id/edit',name:'admin-article-edit',component:AdminArticleEditorPage},{path:'/admin/articles',name:'admin-articles',component:{template:'<p>列表</p>'}}]});await router.push(path);await router.isReady();render({template:'<router-view />'},{global:{plugins:[router],stubs:{MarkdownEditor:editorStub}}});await screen.findByLabelText('标题');return router }
async function fill(){await fireEvent.update(screen.getByLabelText('标题'),'测试文章');await fireEvent.update(screen.getByLabelText('摘要'),'摘要');await fireEvent.update(screen.getByLabelText('正文'),'# 正文')}

describe('AdminArticleEditorPage',()=>{beforeEach(()=>vi.clearAllMocks());afterEach(()=>{cleanup();vi.restoreAllMocks()})
  it('validates required fields without community controls',async()=>{await mount();await fireEvent.click(screen.getByRole('button',{name:'保存草稿'}));expect((await screen.findByRole('alert')).textContent).toContain('请填写标题、摘要和正文');expect(screen.queryByText(/作者|评论管理|点赞|收藏|订阅者/)).toBeNull()})
  it('hydrates an existing draft and preserves its cover media id on save',async()=>{const api=await import('../admin-api');vi.mocked(api.loadAdminArticle).mockResolvedValue({id:3,title:'旧稿',slug:'old',summary:'摘要',markdownContent:'# old',contentType:'ARTICLE',status:'DRAFT',publishedAt:null,scheduledAt:null,coverUrl:'/cover',coverMediaId:9,category:null,tags:[],topic:null,seoTitle:null,seoDescription:null,renderedHtml:''});vi.mocked(api.updateArticle).mockResolvedValue({id:3} as never);await mount('/admin/articles/3/edit');await fireEvent.click(screen.getByRole('button',{name:'保存草稿'}));expect(api.updateArticle).toHaveBeenCalledWith(3,expect.objectContaining({title:'旧稿',coverMediaId:9}))})
  it('blocks router navigation and beforeunload while dirty',async()=>{const router=await mount();await fireEvent.update(screen.getByLabelText('标题'),'未保存');const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);expect(event.defaultPrevented).toBe(true);await router.push('/admin/articles');expect(router.currentRoute.value.path).toBe('/admin/articles/new');expect(confirm).toHaveBeenCalled()})
  it('publishes after saving and schedules with explicit Shanghai offset',async()=>{const api=await import('../admin-api');vi.mocked(api.createArticle).mockResolvedValue({id:7} as never);vi.mocked(api.publishArticle).mockResolvedValue({id:7} as never);vi.mocked(api.scheduleArticle).mockResolvedValue({id:7} as never);await mount();await fill();await fireEvent.click(screen.getByRole('button',{name:'发布设置'}));await fireEvent.update(await screen.findByLabelText('计划发布时间'),'2099-08-23T10:30');await fireEvent.click(screen.getByRole('button',{name:'计划发布'}));await waitFor(()=>expect(api.scheduleArticle).toHaveBeenCalledWith(7,'2099-08-23T10:30:00+08:00'))})
  it('distinguishes a slug conflict from another 409 problem',async()=>{const api=await import('../admin-api');vi.mocked(api.createArticle).mockRejectedValueOnce(new ApiProblem({title:'Conflict',status:409,detail:'Article slug already exists'})).mockRejectedValueOnce(new ApiProblem({title:'Conflict',status:409,detail:'Archived content cannot be edited'}));await mount();await fill();await fireEvent.click(screen.getByRole('button',{name:'保存草稿'}));expect((await screen.findByRole('alert')).textContent).toContain('固定链接已存在');await fireEvent.click(screen.getByRole('button',{name:'保存草稿'}));expect((await screen.findByRole('alert')).textContent).toBe('Archived content cannot be edited')})
  it('keeps edits made while a save request is pending dirty',async()=>{const api=await import('../admin-api');let resolve!:(value:any)=>void;vi.mocked(api.createArticle).mockReturnValue(new Promise(r=>{resolve=r}));const router=await mount();await fill();await fireEvent.click(screen.getByRole('button',{name:'保存草稿'}));await fireEvent.update(screen.getByLabelText('标题'),'请求期间的新标题');resolve({id:7,status:'DRAFT'});await waitFor(()=>expect(api.createArticle).toHaveBeenCalled());const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);await router.push('/admin/articles');expect(router.currentRoute.value.path).toBe('/admin/articles/new');expect(confirm).toHaveBeenCalled()})
  it('keeps edits made while publish is pending dirty after the published snapshot returns',async()=>{const api=await import('../admin-api');let resolvePublish!:(value:any)=>void;vi.mocked(api.createArticle).mockResolvedValue({id:7,status:'DRAFT'} as never);vi.mocked(api.publishArticle).mockReturnValue(new Promise(r=>{resolvePublish=r}));const router=await mount();await fill();await fireEvent.click(screen.getByRole('button',{name:'发布设置'}));await fireEvent.click(await screen.findByRole('button',{name:'立即发布'}));await fireEvent.update(screen.getByLabelText('标题'),'发布期间的新标题');resolvePublish({id:7,status:'PUBLISHED'});await waitFor(()=>expect(api.publishArticle).toHaveBeenCalledWith(7));const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);await router.push('/admin/articles');expect(router.currentRoute.value.path).toContain('/admin/articles/7/edit');expect(confirm).toHaveBeenCalled()})
  it('locks duplicate and cross state actions, restores actions after failure, and preserves pending edits',async()=>{const api=await import('../admin-api');let rejectPublish!:(reason:unknown)=>void;vi.mocked(api.createArticle).mockResolvedValue({id:7,status:'DRAFT'} as never);vi.mocked(api.publishArticle).mockReturnValue(new Promise((_,reject)=>{rejectPublish=reject}));vi.mocked(api.scheduleArticle).mockResolvedValue({id:7,status:'SCHEDULED'} as never);const router=await mount();await fill();await fireEvent.click(screen.getByRole('button',{name:'发布设置'}));await fireEvent.update(await screen.findByLabelText('计划发布时间'),'2099-08-23T10:30');await fireEvent.click(screen.getByRole('button',{name:'立即发布'}));expect((screen.getByRole('button',{name:'处理中…'}) as HTMLButtonElement).disabled).toBe(true);expect((screen.getByRole('button',{name:'计划发布'}) as HTMLButtonElement).disabled).toBe(true);expect((screen.getByRole('button',{name:'取消'}) as HTMLButtonElement).disabled).toBe(true);await fireEvent.click(screen.getByRole('button',{name:'处理中…'}));await fireEvent.click(screen.getByRole('button',{name:'计划发布'}));expect(api.publishArticle).toHaveBeenCalledTimes(1);expect(api.scheduleArticle).not.toHaveBeenCalled();await fireEvent.update(screen.getByLabelText('标题'),'请求期间的新标题');rejectPublish(new ApiProblem({title:'Failure',status:503,detail:'发布服务暂不可用'}));expect((await screen.findByRole('alert')).textContent).toBe('发布服务暂不可用');await waitFor(()=>expect((screen.getByRole('button',{name:'立即发布'}) as HTMLButtonElement).disabled).toBe(false));await fireEvent.click(screen.getByRole('button',{name:'计划发布'}));await waitFor(()=>expect(api.scheduleArticle).toHaveBeenCalledTimes(1));const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);await router.push('/admin/articles');expect(router.currentRoute.value.path).toContain('/admin/articles/7/edit');expect(confirm).toHaveBeenCalled()})
  it('only exposes legal draft actions and actually publishes immediately',async()=>{const api=await import('../admin-api');vi.mocked(api.loadAdminArticle).mockResolvedValue({id:3,title:'旧稿',slug:'old',summary:'摘要',markdownContent:'# old',contentType:'ARTICLE',status:'DRAFT',publishedAt:null,scheduledAt:null,coverUrl:null,coverMediaId:null,category:null,tags:[],topic:null,seoTitle:null,seoDescription:null,renderedHtml:''});vi.mocked(api.updateArticle).mockResolvedValue({id:3,status:'DRAFT'} as never);vi.mocked(api.publishArticle).mockResolvedValue({id:3,status:'PUBLISHED'} as never);await mount('/admin/articles/3/edit');expect(screen.queryByRole('button',{name:'归档'})).toBeNull();await fireEvent.click(screen.getByRole('button',{name:'发布设置'}));await fireEvent.click(await screen.findByRole('button',{name:'立即发布'}));await waitFor(()=>expect(api.publishArticle).toHaveBeenCalledWith(3));expect(screen.queryByRole('button',{name:'发布设置'})).toBeNull();expect(screen.getByRole('button',{name:'归档'})).toBeTruthy()})
  it('requires an accessible focused confirmation before archiving a published article',async()=>{const api=await import('../admin-api');vi.mocked(api.loadAdminArticle).mockResolvedValue({id:3,title:'旧稿',slug:'old',summary:'摘要',markdownContent:'# old',contentType:'ARTICLE',status:'PUBLISHED',publishedAt:'x',scheduledAt:null,coverUrl:null,coverMediaId:null,category:null,tags:[],topic:null,seoTitle:null,seoDescription:null,renderedHtml:''});vi.mocked(api.archiveArticle).mockResolvedValue({id:3,status:'ARCHIVED'} as never);await mount('/admin/articles/3/edit');await fireEvent.click(screen.getByRole('button',{name:'归档'}));const dialog=screen.getByRole('dialog',{name:'确认归档？',description:'归档后内容将不再公开展示。'});expect(dialog).toBeTruthy();expect(document.activeElement).toBe(screen.getByRole('button',{name:'确认归档'}));expect(api.archiveArticle).not.toHaveBeenCalled();await fireEvent.click(screen.getByRole('button',{name:'确认归档'}));await waitFor(()=>expect(api.archiveArticle).toHaveBeenCalledWith(3))})
})
